global:
  resolve_timeout: 5m

route:
  receiver: "telegram"
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 1h

receivers:
  - name: "telegram"
    telegram_configs:
      - send_resolved: true
        bot_token: "7920437249:AAFHucmnlKgeqkd-n19xFoM8aiBP-oR-NYg"
        chat_id: 6793955595
        message: "🚨 *ALERT:* {{ .CommonAnnotations.summary }}\n*Description1:* {{ .CommonAnnotations.description }}"
        parse_mode: "Markdown"
