version: "3.8"

services:
  prometheus:
    image: prom/prometheus:v2.53.4
    container_name: prometheus
    volumes:
      - ./prometheus:/etc/prometheus
    ports:
      - "9090:9090"
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
    restart: unless-stopped

  alertmanager:
    image: prom/alertmanager
    container_name: alertmanager
    volumes:
      - ./alertmanager:/etc/alertmanager
    ports:
      - "9093:9093"
    dns:
      - 8.8.8.8
    command:
      - "--config.file=/etc/alertmanager/alertmanager.yml"
    restart: unless-stopped

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    restart: unless-stopped

#services:
#  prometheus:
#    image: prom/prometheus:v2.53.4
#    container_name: prometheus
#    volumes:
#      - ./prometheus:/etc/prometheus
#    ports:
#      - "9090:9090"
#    command:
#      - "--config.file=/etc/prometheus/prometheus.yml"
#      - "--storage.tsdb.path=/prometheus"
#    restart: unless-stopped#

#  alertmanager:
#    image: prom/alertmanager
#    container_name: alertmanager
#    volumes:
#      - ./alertmanager:/etc/alertmanager
#    ports:
#      - "9093:9093"
#    dns:
#      - 8.8.8.8
#    command:
#      - "--config.file=/etc/alertmanager/alertmanager.yml"
#    restart: unless-stopped

#  grafana:
#    image: grafana/grafana
#    container_name: grafana
#    ports:
#      - "3000:3000"
#    volumes:
#      - ./grafana:/var/lib/grafana
#    restart: unless-stopped

  telegram-bot:
    build:
      context: ./telegram-bot
    container_name: telegram-bot
    restart: unless-stopped
